### ISSUE TITLE
Dashboard shows last disconnection with wrong format in devices page

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte-dashboard#198]
See attached screenshot below
![2020-10-04-181226_292x95_scrot](https://user-images.githubusercontent.com/2528778/95020746-3f694e80-066d-11eb-85aa-e4dc980be949.png)
I would expect DD/MM/YYYY or YYYY/MM/DD, while currently it seems it uses MM/DD/YYYY

**Comment by Pavinati** [comment]
It uses the browser locale. Are you using a en_bg locale on your OS or your browser?

**Comment by davidebriani** [comment]
To expand on the issue, date formatting is currently done with `Date(...).toLocaleString()`.
Calling `toLocaleString()` without specifying a locale will result in a lookup for the browser's locale, i.e. the locale the browser was compiled in or the locale from the OS settings.
The same value can be obtained from `Intl.DateTimeFormat().resolvedOptions().locale`.

However the resulting language could be different from what the user is expecting, since he could have specified a different choice in the Browser settings, listing some (different) preferred locales.
This choice can be arguably more relevant but it seems there's no reliable way to retrieve it other than something like:
`(navigator.languages && navigator.languages.length) ? navigator.languages[0] : (navigator.userLanguage || navigator.language || navigator.browserLanguage || 'en')`.

Given the above, we could:
1) agree on a single standard format that avoids displaying ambiguous dates, maybe `YYYY-MM-DD`.
2) use a longer format to display months in letters instead of numbers: `Date(...).toLocaleString([], { dateStyle: 'long', timeStyle: 'medium' })` results in `February 8, 2021 at 12:38:13 PM`
