### ISSUE TITLE
Filter implementation is not usable when more devices are registered in Astarte

### ISSUE THREAD

**Issue by nanjarapalli** [astarte-platform/astarte-dashboard#359]
**Setup**

- 60K+ devices are registered in Astarte
- Astarte Dashboard v1.0.4

**Observation/Issues**

- Too many API requests to search a single device
- Too much network usage to search a single device
- Duplicates are displayed
- Takes a long time to find a device and no status of searching is indicated to the user
- Due to the missing status of the search, the user may try to use filter options a second time and this makes it even worse that requests are doubled (See inspect in the video)
- Shows no device matches even though the device exists
- Gigabytes of memory usage by the browser

https://user-images.githubusercontent.com/16062109/204317073-70763bf4-a6de-40a3-aa19-ac31323dc4bc.mp4

**Comment by davidebriani** [comment]
As pointed out, the main issues for the UX of the search functionality are dependent upon what Astarte APIs have to offer.
As such, optimal solutions will have to wait for the future versions of Astarte.
The other inconsistencies are already fixed, so I'm closing this issue since astarte-platform/astarte#747 will track further developments on the matter.
