### ISSUE TITLE
Cannot remove `explicit_timestamp` from an existing mapping

### ISSUE THREAD

**Issue by sorru94** [astarte-platform/astarte-dashboard#387]
Removing `explicit_timestamp` from an existing mapping while bumping only the minor version is not allowed by the dashboard.
Error message returned is:
```
Could not update interface: Request failed with status code 409
```

**Comment by sorru94** [comment]
Reproduce with:
```
{
    "interface_name": "org.astarte-platform.Example",
    "version_major": 0,
    "version_minor": 1,
    "type": "datastream",
    "ownership": "device",
    "mappings": [
        {
            "endpoint": "/example_mapping",
            "type": "double",
            "explicit_timestamp": true
        }
    ]
}
```
And then try to update it with:
```
{
    "interface_name": "org.astarte-platform.Example",
    "version_major": 0,
    "version_minor": 2,
    "type": "datastream",
    "ownership": "device",
    "mappings": [
        {
            "endpoint": "/example_mapping",
            "type": "double"
        }
    ]
}
```
This results in a success but does not actually remove the timestamp.

**Comment by sorru94** [comment]
Note that if the `version_minor` is updated through the GUI before the removal of the `explicit_timestamp` field, the operation might trigger a success result. However, the interface is not actually updated correctly and the `explicit_timestamp` field remains.

**Comment by davidebriani** [comment]
@Hibe7 I think that @sorru94 has a point: the Astarte Dashboard should let you remove/add the `explicit_timestamp` field between minor versions of an interface.
This is because Astarte contemplates such a change; you can test that is true by using astartectl to install updates to the interface's definition:
```
astartectl realm-management interfaces sync org.astarte-platform.Example.json --astarte-url <base astarte API url> -r <realm> -k <path to realm's private key file>
```
where `org.astarte-platform.Example.json` contains the interface's definition.
Astarte happily installs the updates.
