### ISSUE TITLE
Device page registering to live events twice

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astarte-dashboard#435]
In the current `master` branch (v1.2.0-dev) the device page registers to device events twice, probably due to a component rerender
![Screenshot_20240424_145427](https://github.com/astarte-platform/astarte-dashboard/assets/5071605/816851b4-80d4-42ca-bd37-a707e0eee0f7)

**Comment by Hibe7** [comment]
I have investigated this issue a little and I found that React version is changed from 17 to 18. This change could be causing the problem because, starting from React 18, `Strict Mode` intentionally double-renders components to help identify potential issues. As a result, this [useEffect](https://github.com/astarte-platform/astarte-dashboard/blob/7e0ee55650d7770921de3e1429a756d8041c4b70/src/DeviceStatusPage/DeviceLiveEventsCard.tsx#L376) is executed twice, leading to the opening of two WebSocket connections and the appearance of duplicate data. 
`Strict mode` double-renders components twice just in development mode, in production it renders once. If you want to fix this in development mode we can remove `strict mode`, that is one solution, or we can use `useRef` hook and use `if statement` to prevent second execution of `useEffect` that I mentioned above.
